sudo: required

language: python

services:
  - docker

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run pycodestyle reserve_sdk/*.py
  - pipenv run pytest --verbose
